(* [smtp_domain] is the domain of your SMTP service.
 * [ssh_key] is the seed generated by [awa_gen_key] (RSA key)
 * [dns_personal_key] is the personal key to [nsupdate] your primary DNS server
 * [letsencrypt_account_key] can be a random seed
 * [dkim_key] can be a random seed *)

let smtp_domain : string = failwith "SMTP domain is required"
let ssh_key : string = failwith "Git SSH key is required"
let dns_personal_key : string = failwith "DNS personal key is required"

let letsencrypt_account_key : string =
  failwith "Let's encrypt account key is required"

let dkim_key : string = failwith "DKIM private key is required"
